import { describe, expect, it } from 'vitest'
import { formatDanceScheduleMarkdown } from './formatDanceScheduleMarkdown'
import type { DanceSession } from '../types/danceSchedule'

describe('formatDanceScheduleMarkdown', () => {
  it('renders a header and one table section per date', () => {
    const sessions: DanceSession[] = [
      {
        kind: 'structured',
        date: new Date('2026-07-02T00:00:00.000Z'),
        startTime: new Date('2026-07-02T12:30:00.000Z'),
        endTime: new Date('2026-07-02T13:30:00.000Z'),
        location: { kind: 'located', rooms: ['Kafka/Lamartine'] },
        levels: ['C1', 'C2'],
        eventType: 'Dancing',
        callers: ['Vic Ceder'],
      },
    ]

    const markdown = formatDanceScheduleMarkdown(sessions)

    expect(markdown).toContain('# Dance schedule — parsed dump')
    expect(markdown).toContain('Auto-generated by `vite-plugin-dance-schedule.ts`')
    expect(markdown).toContain('## Thursday, July 2, 2026')
    expect(markdown).toContain('| Time | Room | Level(s) | Details | GCA |')
    expect(markdown).toContain(
      '| 12:30 PM – 1:30 PM | Kafka/Lamartine | C1, C2 | Dancing - Vic Ceder |  |',
    )
  })

  it('renders a GCA value when present', () => {
    const sessions: DanceSession[] = [
      {
        kind: 'structured',
        date: new Date('2026-07-02T00:00:00.000Z'),
        startTime: new Date('2026-07-02T12:30:00.000Z'),
        endTime: new Date('2026-07-02T13:30:00.000Z'),
        location: { kind: 'located', rooms: ['Hemon'] },
        levels: ['Plus'],
        eventType: 'Dancing',
        callers: ['Kris Jensen'],
        gca: 'Tim Stephens',
      },
    ]

    expect(formatDanceScheduleMarkdown(sessions)).toContain(
      '| 12:30 PM – 1:30 PM | Hemon | Plus | Dancing - Kris Jensen | Tim Stephens |',
    )
  })

  it('renders multiple co-primary callers joined by "&"', () => {
    const sessions: DanceSession[] = [
      {
        kind: 'structured',
        date: new Date('2026-07-02T00:00:00.000Z'),
        startTime: new Date('2026-07-02T19:00:00.000Z'),
        endTime: new Date('2026-07-02T20:00:00.000Z'),
        location: { kind: 'located', rooms: ['Ballroom West'] },
        levels: ['SSD'],
        eventType: 'Leather Tip',
        callers: ['Michael Kellogg', 'Terri Sherrer'],
      },
    ]

    expect(formatDanceScheduleMarkdown(sessions)).toContain(
      'Leather Tip - Michael Kellogg & Terri Sherrer',
    )
  })

  it('renders a freeform session distinctly, with no levels or GCA', () => {
    const sessions: DanceSession[] = [
      {
        kind: 'freeform',
        date: new Date('2026-07-04T00:00:00.000Z'),
        startTime: new Date('2026-07-04T21:00:00.000Z'),
        endTime: new Date('2026-07-04T21:30:00.000Z'),
        location: { kind: 'located', rooms: ['Drummond Ballroom'] },
        description: 'Country Western Dance - until 1am',
      },
    ]

    expect(formatDanceScheduleMarkdown(sessions)).toContain(
      '| 9:00 PM – 9:30 PM | Drummond Ballroom |  | *(freeform)* Country Western Dance - until 1am |  |',
    )
  })

  it('collapses an embedded newline in a description so it stays on one table row', () => {
    const sessions: DanceSession[] = [
      {
        kind: 'freeform',
        date: new Date('2026-07-04T00:00:00.000Z'),
        startTime: new Date('2026-07-04T21:00:00.000Z'),
        endTime: new Date('2026-07-04T21:30:00.000Z'),
        location: { kind: 'located', rooms: ['Drummond Ballroom'] },
        description: 'Line one\nLine two',
      },
    ]

    const markdown = formatDanceScheduleMarkdown(sessions)
    const tableLines = markdown.split('\n').filter((line) => line.startsWith('|'))

    // Exactly 3 pipe-prefixed lines: the header, the separator, and one data row —
    // if the newline weren't collapsed, the row would split into two lines instead.
    expect(tableLines).toHaveLength(3)
    expect(markdown).toContain('*(freeform)* Line one Line two')
  })

  it('renders a roomless session with a placeholder instead of a blank Room cell', () => {
    const sessions: DanceSession[] = [
      {
        kind: 'freeform',
        date: new Date('2026-07-03T00:00:00.000Z'),
        startTime: new Date('2026-07-03T17:00:00.000Z'),
        endTime: new Date('2026-07-03T18:30:00.000Z'),
        location: { kind: 'roomless' },
        description: 'Lunch Break',
      },
    ]

    expect(formatDanceScheduleMarkdown(sessions)).toContain(
      '| 5:00 PM – 6:30 PM | — |  | *(freeform)* Lunch Break |  |',
    )
  })

  it('renders a multi-room session\'s rooms joined by ", "', () => {
    const sessions: DanceSession[] = [
      {
        kind: 'structured',
        date: new Date('2026-07-03T00:00:00.000Z'),
        startTime: new Date('2026-07-03T10:15:00.000Z'),
        endTime: new Date('2026-07-03T11:00:00.000Z'),
        location: { kind: 'located', rooms: ['Ballroom Centre', 'Ballroom East'] },
        levels: ['SSD'],
        eventType: 'All Callers Dance',
        callers: ['All Callers'],
      },
    ]

    expect(formatDanceScheduleMarkdown(sessions)).toContain(
      '| 10:15 AM – 11:00 AM | Ballroom Centre, Ballroom East | SSD | All Callers Dance - All Callers |  |',
    )
  })

  it('creates a separate section per distinct date', () => {
    const sessions: DanceSession[] = [
      {
        kind: 'freeform',
        date: new Date('2026-07-02T00:00:00.000Z'),
        startTime: new Date('2026-07-02T12:00:00.000Z'),
        endTime: new Date('2026-07-02T13:00:00.000Z'),
        location: { kind: 'located', rooms: ['Hemon'] },
        description: 'Day one',
      },
      {
        kind: 'freeform',
        date: new Date('2026-07-03T00:00:00.000Z'),
        startTime: new Date('2026-07-03T12:00:00.000Z'),
        endTime: new Date('2026-07-03T13:00:00.000Z'),
        location: { kind: 'located', rooms: ['Hemon'] },
        description: 'Day two',
      },
    ]

    const markdown = formatDanceScheduleMarkdown(sessions)
    expect(markdown).toContain('## Thursday, July 2, 2026')
    expect(markdown).toContain('## Friday, July 3, 2026')
  })
})
