import {
  computeDanceScheduleHourSummary,
  formatHours,
  type DanceScheduleHourSummaryRow,
} from './computeDanceScheduleHourSummary'
import { groupDanceSessionsByDate } from './groupDanceSessionsByDate'
import {
  formatSessionCallerDetails,
  formatSessionGca,
  formatSessionLevels,
  formatSessionRoom,
  formatSessionTimeRange,
} from './formatDanceSession'
import type { DanceSession } from '../types/danceSchedule'

const dateFormatter = new Intl.DateTimeFormat('en-US', { dateStyle: 'full', timeZone: 'UTC' })
// Short enough to use as a table column header, unlike dateFormatter's full form —
// matches DanceScheduleFilters.tsx's own date-select convention.
const columnDateFormatter = new Intl.DateTimeFormat('en-US', {
  weekday: 'short',
  month: 'short',
  day: 'numeric',
  timeZone: 'UTC',
})

function formatDetails(session: DanceSession): string {
  const details = formatSessionCallerDetails(session)
  return session.kind === 'freeform' ? `*(freeform)* ${details}` : details
}

function escapeCell(value: string): string {
  // A raw newline (e.g. from a multi-line freeform description) would otherwise
  // break the generated table row across multiple physical lines.
  return value.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ')
}

function formatHourSummaryTable(
  heading: string,
  firstColumnHeading: string,
  dates: Date[],
  rows: DanceScheduleHourSummaryRow[],
): string {
  const dateHeadings = dates.map((date) => columnDateFormatter.format(date))
  const tableRows = rows.map((row) =>
    [row.label, ...row.hoursByDate.map(formatHours), formatHours(row.total)].join(' | '),
  )

  return [
    `## ${heading}`,
    '',
    `| ${firstColumnHeading} | ${dateHeadings.join(' | ')} | Total |`,
    `| ${['---', ...dateHeadings.map(() => '---'), '---'].join(' | ')} |`,
    ...tableRows.map((row) => `| ${row} |`),
  ].join('\n')
}

function formatSection(group: { date: Date; sessions: DanceSession[] }): string {
  const rows = group.sessions.map((session) =>
    [
      formatSessionTimeRange(session),
      formatSessionRoom(session),
      formatSessionLevels(session),
      formatDetails(session),
      formatSessionGca(session),
    ]
      .map(escapeCell)
      .join(' | '),
  )

  return [
    `## ${dateFormatter.format(group.date)}`,
    '',
    '| Time | Room | Level(s) | Details | GCA |',
    '| --- | --- | --- | --- | --- |',
    ...rows.map((row) => `| ${row} |`),
  ].join('\n')
}

/**
 * Produces a normalized, human-readable markdown dump of the parsed dance
 * schedule — one table per date, sorted chronologically — so a change to the
 * source spreadsheet's interpretation is easy to eyeball or diff. Generated at
 * build time by vite-plugin-dance-schedule.ts into dance-schedule-dump.md,
 * alongside the active content set's dance-schedule.xlsx.
 */
export function formatDanceScheduleMarkdown(sessions: DanceSession[]): string {
  const groups = groupDanceSessionsByDate(sessions)
  const summary = computeDanceScheduleHourSummary(sessions)

  return [
    '# Dance schedule — parsed dump',
    '_Auto-generated by `vite-plugin-dance-schedule.ts` at build time from' +
      ' this content set\'s `dance-schedule.xlsx` — do not hand-edit._',
    formatHourSummaryTable('Hours by level', 'Level', summary.dates, summary.levelRows),
    formatHourSummaryTable('Hours by caller', 'Caller', summary.dates, summary.callerRows),
    ...groups.map(formatSection),
  ].join('\n\n')
}
