import {
  computeDanceScheduleHourSummary,
  formatHours,
  type DanceScheduleHourSummaryTable,
} from './computeDanceScheduleHourSummary'
import { groupDanceSessionsByDate } from './groupDanceSessionsByDate'
import {
  formatSessionCallerDetails,
  formatSessionGca,
  formatSessionLevels,
  formatSessionRoom,
  formatSessionTimeRange,
} from './formatDanceSession'
import type { DanceSession } from '../types/danceSchedule'

const dateFormatter = new Intl.DateTimeFormat('en-US', { dateStyle: 'full', timeZone: 'UTC' })
// Short enough to use as a table column header, unlike dateFormatter's full form —
// matches DanceScheduleFilters.tsx's own date-select convention.
const columnDateFormatter = new Intl.DateTimeFormat('en-US', {
  weekday: 'short',
  month: 'short',
  day: 'numeric',
  timeZone: 'UTC',
})

function formatDetails(session: DanceSession): string {
  const details = formatSessionCallerDetails(session)
  return session.kind === 'freeform' ? `*(freeform)* ${details}` : details
}

function escapeCell(value: string): string {
  // A raw newline (e.g. from a multi-line freeform description) would otherwise
  // break the generated table row across multiple physical lines.
  return value.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ')
}

// One row per date (plus a final Total row), one column per level/caller (plus a
// final Total column) — a day-by-day cross-tab, transposed from
// computeDanceScheduleHourSummary's own column-oriented shape purely at render time
// (see RawDanceScheduleTable.tsx's identical transposition).
function formatHourSummaryTable(heading: string, dates: Date[], table: DanceScheduleHourSummaryTable): string {
  const columnHeadings = table.columns.map((column) => column.label)
  const dateRows = dates.map((date, dateIndex) =>
    [
      columnDateFormatter.format(date),
      ...table.columns.map((column) => formatHours(column.hoursByDate[dateIndex]!)),
      formatHours(table.totalByDate[dateIndex]!),
    ].join(' | '),
  )
  const totalRow = [
    'Total',
    ...table.columns.map((column) => formatHours(column.total)),
    formatHours(table.grandTotal),
  ].join(' | ')

  return [
    `## ${heading}`,
    '',
    // Array-joined, not naive template interpolation — with zero columns (an
    // empty `columnHeadings`), interpolating its own join() directly between two
    // literal " | " separators would leave a stray empty cell between Date and
    // Total; joining one shared array with everything already in it doesn't.
    `| ${['Date', ...columnHeadings, 'Total'].join(' | ')} |`,
    `| ${['---', ...columnHeadings.map(() => '---'), '---'].join(' | ')} |`,
    ...dateRows.map((row) => `| ${row} |`),
    `| ${totalRow} |`,
  ].join('\n')
}

function formatSection(group: { date: Date; sessions: DanceSession[] }): string {
  const rows = group.sessions.map((session) =>
    [
      formatSessionTimeRange(session),
      formatSessionRoom(session),
      formatSessionLevels(session),
      formatDetails(session),
      formatSessionGca(session),
    ]
      .map(escapeCell)
      .join(' | '),
  )

  return [
    `## ${dateFormatter.format(group.date)}`,
    '',
    '| Time | Room | Level(s) | Details | GCA |',
    '| --- | --- | --- | --- | --- |',
    ...rows.map((row) => `| ${row} |`),
  ].join('\n')
}

/**
 * Produces a normalized, human-readable markdown dump of the parsed dance
 * schedule — one table per date, sorted chronologically — so a change to the
 * source spreadsheet's interpretation is easy to eyeball or diff. Generated at
 * build time by vite-plugin-dance-schedule.ts into dance-schedule-dump.md,
 * alongside the active content set's dance-schedule.xlsx.
 */
export function formatDanceScheduleMarkdown(sessions: DanceSession[]): string {
  const groups = groupDanceSessionsByDate(sessions)
  const summary = computeDanceScheduleHourSummary(sessions)

  return [
    '# Dance schedule — parsed dump',
    '_Auto-generated by `vite-plugin-dance-schedule.ts` at build time from' +
      ' this content set\'s `dance-schedule.xlsx` — do not hand-edit._',
    formatHourSummaryTable('Hours by level', summary.dates, summary.levels),
    formatHourSummaryTable('Hours by caller', summary.dates, summary.callers),
    ...groups.map(formatSection),
  ].join('\n\n')
}
