import { describe, expect, it } from 'vitest'
import { formatDetailedScheduleMarkdown } from './formatDetailedScheduleMarkdown'
import type { DetailedSession } from '../types/detailedSchedule'

describe('formatDetailedScheduleMarkdown', () => {
  it('renders a header and one table section per date', () => {
    const sessions: DetailedSession[] = [
      {
        kind: 'structured',
        date: new Date('2026-07-02T00:00:00.000Z'),
        startTime: new Date('2026-07-02T12:30:00.000Z'),
        endTime: new Date('2026-07-02T13:30:00.000Z'),
        room: 'Kafka/Lamartine',
        levels: ['C1', 'C2'],
        eventType: 'Dancing',
        callers: ['Vic Ceder'],
      },
    ]

    const markdown = formatDetailedScheduleMarkdown(sessions)

    expect(markdown).toContain('# Detailed schedule — parsed dump')
    expect(markdown).toContain('Auto-generated by `vite-plugin-detailed-schedule.ts`')
    expect(markdown).toContain('## Thursday, July 2, 2026')
    expect(markdown).toContain('| Time | Room | Level(s) | Details | GCA |')
    expect(markdown).toContain(
      '| 12:30 PM – 1:30 PM | Kafka/Lamartine | C1, C2 | Dancing - Vic Ceder |  |',
    )
  })

  it('renders a GCA value when present', () => {
    const sessions: DetailedSession[] = [
      {
        kind: 'structured',
        date: new Date('2026-07-02T00:00:00.000Z'),
        startTime: new Date('2026-07-02T12:30:00.000Z'),
        endTime: new Date('2026-07-02T13:30:00.000Z'),
        room: 'Hemon',
        levels: ['Plus'],
        eventType: 'Dancing',
        callers: ['Kris Jensen'],
        gca: 'Tim Stephens',
      },
    ]

    expect(formatDetailedScheduleMarkdown(sessions)).toContain(
      '| 12:30 PM – 1:30 PM | Hemon | Plus | Dancing - Kris Jensen | Tim Stephens |',
    )
  })

  it('renders multiple co-primary callers joined by "&"', () => {
    const sessions: DetailedSession[] = [
      {
        kind: 'structured',
        date: new Date('2026-07-02T00:00:00.000Z'),
        startTime: new Date('2026-07-02T19:00:00.000Z'),
        endTime: new Date('2026-07-02T20:00:00.000Z'),
        room: 'Ballroom West',
        levels: ['SSD'],
        eventType: 'Leather Tip',
        callers: ['Michael Kellogg', 'Terri Sherrer'],
      },
    ]

    expect(formatDetailedScheduleMarkdown(sessions)).toContain(
      'Leather Tip - Michael Kellogg & Terri Sherrer',
    )
  })

  it('renders a freeform session distinctly, with no levels or GCA', () => {
    const sessions: DetailedSession[] = [
      {
        kind: 'freeform',
        date: new Date('2026-07-04T00:00:00.000Z'),
        startTime: new Date('2026-07-04T21:00:00.000Z'),
        endTime: new Date('2026-07-04T21:30:00.000Z'),
        room: 'Drummond Ballroom',
        description: 'Country Western Dance - until 1am',
      },
    ]

    expect(formatDetailedScheduleMarkdown(sessions)).toContain(
      '| 9:00 PM – 9:30 PM | Drummond Ballroom |  | *(freeform)* Country Western Dance - until 1am |  |',
    )
  })

  it('creates a separate section per distinct date', () => {
    const sessions: DetailedSession[] = [
      {
        kind: 'freeform',
        date: new Date('2026-07-02T00:00:00.000Z'),
        startTime: new Date('2026-07-02T12:00:00.000Z'),
        endTime: new Date('2026-07-02T13:00:00.000Z'),
        room: 'Hemon',
        description: 'Day one',
      },
      {
        kind: 'freeform',
        date: new Date('2026-07-03T00:00:00.000Z'),
        startTime: new Date('2026-07-03T12:00:00.000Z'),
        endTime: new Date('2026-07-03T13:00:00.000Z'),
        room: 'Hemon',
        description: 'Day two',
      },
    ]

    const markdown = formatDetailedScheduleMarkdown(sessions)
    expect(markdown).toContain('## Thursday, July 2, 2026')
    expect(markdown).toContain('## Friday, July 3, 2026')
  })
})
