// Regenerates the "- Hours by Level"/"- Hours by Caller" summary tabs inside
// content/backtrack2abq/data/dance-schedule.xlsx — static snapshots of the same
// two tables the /debug/dance-schedule page computes and displays
// (computeDanceScheduleHourSummary.ts), so anyone opening the real spreadsheet
// in Excel sees the same totals without visiting the app. The caller table
// omits that page's own 3-hour floor (minCallerHours: 0 below) — every caller
// with any measured hours appears, per direct product decision to keep this
// spreadsheet's version simpler than the debug page's own curated one. GCA
// credit is never counted toward anyone's hours, matching
// computeDanceScheduleHourSummary's own existing behavior — no extra work
// needed for that.
//
// A permanent, reusable tool (like scripts/edit-test-data.mjs), not a one-off —
// RE-RUN THIS anytime a day's schedule in the workbook changes. These two tabs
// are static values, not live formulas (see docs/design/dance-schedule.md for
// why: the source cells are compound parsed strings, not something a plain
// Excel formula can re-derive) — they go stale otherwise.
//
// Both tab names start with "-" so the real build's own parser
// (isNonScheduleSheetName, parseDanceScheduleSheet.ts) treats them as
// non-schedule content and skips them, rather than trying (and failing) to
// parse them as another day's schedule.
//
// Usage: node --import=tsx scripts/generate-dance-schedule-hour-tabs.ts
// (NOT `pnpm exec tsx ...`/the bare `tsx` CLI — its IPC-socket setup fails with
// EPERM in at least one sandboxed environment this was developed in; `node
// --import=tsx` runs the identical transform without that wrapper, including
// resolving this script's own relative .ts imports correctly.)

import ExcelJS from 'exceljs'
import { loadDanceScheduleData } from '../vite-plugin-dance-schedule'
import { buildDanceSchedule } from '../src/lib/buildDanceSchedule'
import {
  computeDanceScheduleHourSummary,
  type DanceScheduleHourSummaryTable,
} from '../src/lib/computeDanceScheduleHourSummary'

const WORKBOOK_PATH = 'content/backtrack2abq/data/dance-schedule.xlsx'

// Matches RawDanceScheduleTable.tsx's own columnDateFormatter exactly, so a
// date label here reads identically to the debug page's own column headers.
const dateFormatter = new Intl.DateTimeFormat('en-US', {
  weekday: 'short',
  month: 'short',
  day: 'numeric',
  timeZone: 'UTC',
})

// Both start with "-" — see this file's own header comment for why.
const LEVEL_SHEET_NAME = '- Hours by Level'
const CALLER_SHEET_NAME = '- Hours by Caller'

function writeSummaryTable(
  workbook: ExcelJS.Workbook,
  sheetName: string,
  dates: Date[],
  table: DanceScheduleHourSummaryTable,
) {
  // Idempotency: drop any previous version of this exact sheet before adding a
  // fresh one, rather than depending on ExcelJS's unspecified behavior for a
  // duplicate-name addWorksheet call. Exact-name removal only — deliberately
  // NOT "remove anything '-'-prefixed," which could delete an unrelated
  // utility tab someone else added by hand; that broader rule belongs only to
  // the parser's own skip check (isNonScheduleSheetName), not this script.
  const existing = workbook.getWorksheet(sheetName)
  if (existing) {
    workbook.removeWorksheet(existing.id)
  }

  const sheet = workbook.addWorksheet(sheetName)
  const columnLabels = table.columns.map((column) => column.label)
  const header = ['Date', ...columnLabels, 'Total']
  sheet.addRow(header).font = { bold: true }

  dates.forEach((date, dateIndex) => {
    sheet.addRow([
      dateFormatter.format(date),
      ...table.columns.map((column) => column.hoursByDate[dateIndex]!),
      table.totalByDate[dateIndex]!,
    ])
  })

  sheet.addRow(['Total', ...table.columns.map((column) => column.total), table.grandTotal]).font = {
    bold: true,
  }

  sheet.addRow([])
  sheet.addRow([
    `Generated by scripts/generate-dance-schedule-hour-tabs.ts — re-run after editing any day's schedule.`,
  ])

  // Every hour column (everything after Date) — matches formatHours' own "≤2
  // decimals, no trailing zeros" DISPLAY convention while keeping the
  // underlying stored value at full precision for anyone doing their own math
  // in Excel (see this file's own header comment on why values, not formulas).
  for (let columnIndex = 2; columnIndex <= header.length; columnIndex++) {
    sheet.getColumn(columnIndex).numFmt = '0.##'
  }
}

async function main() {
  const sessionData = await loadDanceScheduleData(WORKBOOK_PATH)
  const sessions = buildDanceSchedule(sessionData)
  const summary = computeDanceScheduleHourSummary(sessions, { minCallerHours: 0 })

  const workbook = new ExcelJS.Workbook()
  await workbook.xlsx.readFile(WORKBOOK_PATH)

  writeSummaryTable(workbook, LEVEL_SHEET_NAME, summary.dates, summary.levels)
  writeSummaryTable(workbook, CALLER_SHEET_NAME, summary.dates, summary.callers)

  await workbook.xlsx.writeFile(WORKBOOK_PATH)
  console.log(`Saved ${WORKBOOK_PATH} with "${LEVEL_SHEET_NAME}"/"${CALLER_SHEET_NAME}" tabs.`)
}

await main()
